services:
  - type: web
    name: makeup-portfolio
    env: python
    plan: free
    buildCommand: ""
    startCommand: gunicorn makeup_project.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: makeup_project.settings
      - key: SECRET_KEY
        value: your-secret-key
      - key: DEBUG
        value: False
