services:
  - type: web
    name: makeup-portfolio
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn makeup_project.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: makeup_project.settings
      - key: SECRET_KEY
        value: uecnd+-8$*!87rre0xoj)z64-td2picgh4*!f7gm#%b2m6%59p
      - key: DEBUG
        value: False
